#!/bin/bash
# 宿主侧包装：从 chroot 启动 Flash-Next W4A16-AutoRound（gavinxym/170hx-2 手册方案）
# 与 start-flash-next-170hx.sh（NVFP4 栈）完全独立：env/日志/缓存另立，互不干扰。
# 用法：
#   bash start-flash-next-w4a16.sh                    # 内置缺省（手册定稿参数, 无投机）
#   FN_SPEC=mtp4 bash start-flash-next-w4a16.sh       # 加 MTP4 投机
#   FN_DRY_RUN=1 bash ...                             # inner 只打印命令
set -u
R=/media/ll/data/vllm-image/rootfs
# 提权口令来源（仓库内不留明文）：CONSOLE_SUDO_PASS 环境变量 → ~/.console-sudo（600）→ 交互输入。
# helper 查找顺序：DEPLOY_DIR → 脚本所在目录 → 上级目录，兼容仓库开发与单文件 scp 上线两种摆放。
CDIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd || true)"
for _csudo_lib in "${DEPLOY_DIR:-/home/ll/deploy}/lib/sudo-pass.sh" ${CDIR:+$CDIR/lib/sudo-pass.sh} ${CDIR:+$CDIR/../lib/sudo-pass.sh}; do
  [ -n "$_csudo_lib" ] && [ -f "$_csudo_lib" ] && { . "$_csudo_lib"; break; }
done
require_sudo_pass || exit 1
require_sudo_pass || exit 1
warm_sudo
# 启动 = 操作者声明实例应在运行：清除人工停止闩锁，恢复看门狗托管（09-26，与新栈同步）
rm -f /home/ll/deploy/fnx-manual-stop
PORT=${FN_PORT:-18420}
LOG=${FN_LOG:-/home/ll/deploy/vllm-flash-next-w4a16.log}
PROF=/home/ll/deploy/flash-next-w4a16-loadprofile.log
ENVFILE=${FN_ENVFILE:-/home/ll/deploy/flash-next-w4a16-launch.env}
RA_LOAD=${RA_LOAD:-128}

# 1) 弹窗参数落盘：透传全部 FN_*（只排除 FN_ENVFILE 自身）
# 【2026-09-26 修复·采样参数静默失效】这里原先是一份手写白名单，漏了 FN_GENCFG：
#   server.js scriptModelLaunchPlan() 已把弹窗采样参数算进 plan.env（日志 summary 里
#   能看到 gen={"temperature":0.1,...,"repetition_penalty":1.2}），但
#     ① 白名单不落盘 FN_GENCFG；
#     ② 本脚本末尾 `sudo -S setsid chroot` 会重置环境（sudo env_reset），弹窗传进来的
#        FN_* 只有写进 ENVFILE 的那部分能进 chroot。
#   ⇒ inner 只能用自己的 GENCFG_DEFAULT（0.6/0.95/20/1.05），弹窗改温度/重复惩罚全无效，
#     控制台「采样参数」卡读的是引擎真实 cmdline，显示 0.6 是真值而非显示 bug。
#   同类漏网还有 FN_CHATKWARGS/FN_PREFIX_CACHE/FN_CHUNKED/FN_SCHED_POLICY/FN_SEED/FN_NOLOG/
#   FN_KV_DTYPE/FN_LIMIT_MM/FN_MAX_SCHED_TOKENS/FN_CPU_OFFLOAD_GB/FN_ENFORCE_EAGER 等
#   （其中一部分 inner 尚未消费，属另一类问题，见 docs/PITFALLS.md）。
# 改为动态扫全部 FN_*：今后 server.js 新增 FN_ 键不必再回来改这张表（原则=参数只有一个
# 权威来源，其余全部透传）。前提：控制台进程环境不含 FN_*（2026-09-26 实测 /proc/<pid>/environ 为空）。
FOUND=0
{
  echo "# generated by start-flash-next-w4a16.sh $(date -Is)"
  for v in $(compgen -e | grep -E '^FN_[A-Z0-9_]+$' | grep -v '^FN_ENVFILE$' | sort); do
    val=$(printenv "$v" 2>/dev/null || true)
    if [ -n "$val" ]; then printf '%s=%q\n' "$v" "$val"; FOUND=1; fi
  done
} > "$ENVFILE"
chmod 644 "$ENVFILE" 2>/dev/null || true
if [ "$FOUND" = "0" ]; then
  rm -f "$ENVFILE"
  echo "[wrapper] $(date -Is) 未收到 FN_* 参数，inner 使用内置缺省（gavinxym 手册定稿 + PLE mmap）" >> "$LOG"
fi

# 2) read_ahead_kb：全程 128 KB（实测拐点，2026-09-23 定版）
#    实测（2T 盘 2.70GB 分片、每轮 fadvise DONTNEED）：0->297 / 128->3011 / 256->3113 /
#    512->3080 / 1024->3301 / 2048->3094 / 8192->3303 MB/s。128KB 已饱和；2048 无吞吐收益
#    且缺页读放大 16x；设 0 会让权重加载慢 10.9x（475s vs 43.7s），绝不可取。
#    机制：内核对 bdi->ra_pages 在 open/mmap 时刻快照进 file->f_ra，事后改 sysfs 对已开 fd
#    无效 ⇒ "加载期高 / 服务期回落 0" 的两段式对已建立的映射不成立，只能全程取一个值。
#    持久化：/etc/udev/rules.d/99-nvme-readahead.rules（按 ENV{ID_SERIAL} 匹配，重启盘符
#    与系统盘互换也不会打错盘）。RA_LOAD=<KB> 可覆盖，但不建议用 0 或 2048。

DEV2T=$(readlink -f /dev/disk/by-id/nvme-JZ-SSD2T-XW_* 2>/dev/null | head -1)
if [ -n "$DEV2T" ] && [ -e "/sys/block/$(basename "$DEV2T")/queue/read_ahead_kb" ]; then
  sudo_run sh -c "echo $RA_LOAD > /sys/block/$(basename '"$DEV2T"')/queue/read_ahead_kb" 2>/dev/null
  echo "[wrapper] read_ahead_kb=$RA_LOAD -> $(basename "$DEV2T")" >> "$LOG"
else
  echo "[wrapper] 未按 by-id 找到数据盘，跳过 read_ahead 设置" >> "$LOG"
fi
: > "$PROF"
if [ -x /home/ll/deploy/flash-next-ra-watch.sh ]; then
  setsid /home/ll/deploy/flash-next-ra-watch.sh "$PORT" >/dev/null 2>&1 &
fi

# 3) 进入 chroot 启动（口令由 lib/sudo-pass.sh 提供；上方 read_ahead 行已预热 sudo 时间戳）
INNER=${INNER:-/home/ll/deploy/flash-next-w4a16-inner.sh}
echo "[wrapper] $(date -Is) inner=$INNER port=$PORT envfile=$ENVFILE" >> "$LOG"
sudo_run setsid chroot $R /bin/bash "$INNER" >> "$LOG" 2>&1
